

services:
  eddn-scanner:
    build: .
    env_file:
    - .env.docker
    # volumes:
    # - yoyo.ini:/app/yoyo.ini
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
