[project]
name = "eddn-scanner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dacite>=1.9.2",
    "tornado>=6.5.1",
    "zmq>=0.0.0",
]
